language: generic
os: osx

install:
- make install

script:
- make

before_deploy:
- make zip
- git fetch --tags

deploy:
  provider: releases
  api_key:
    secure: NNUYr6hAtG8dZay/R1/yYll9sCjcrW+DR9wWHK8IZTztKJgdfXREub/dSuzNtN5aZbsUL3wlePpRHTZSpCDWfJTPBrKQFK1WwhDK4hu8V5301frcIqO3ChhqgzbWuZ8UGhMHt1dc2m6j9aE5ViDbz1EqqYBDm4xESMfc/u0lj3Jf2i+OHy5TSujanFj3XJIoSCMgGZjnTbg+vX6YrF8cqb7fX2VFoZ5cBPN8PfnIMFSOmmOw7ATvyD7+Gmizcv/thH3PZOomDsf7rVDE68tgerfbf/MwmqFcoF0YN3XmfHSVAQXL2HwvUQ2v5ny/tOJDGIfSP5QXT71mM8969wa6EqMP2fgjMEEwR6ikXhwb3Gpq/6KEeHnUzbnZ/ytrAqLWsIEJvaJAno1jMxByLCe/cdOx5ueyi8UQNbxRhBc7c816PZvaABVzA5qOTk2V3dtutY7qqNVySxg98XK+LEaBcSIbrqL4ALDkxioPLw+LGlLzsE3HPxhDgOC4P6vjJ/KnfrjhaoDO1byi1DmHXbPj3ABJMVALeitRG+v4AUnsZmx/IMM4fHBA+PBA5hpIVso7LZQAc3drl+bA4yTAoIczPgWcNwjZvyA366UBBNI0bqIibvW7gVHXRuxfgS6mQNeUBSUI7khe82PCkpFB+nBxmdoK/JMgHWeKfwGK81Lcw3E=
  file:
    - linux_u.zip
    - osx_u.x
    - windows.zip
  skip_cleanup: true
  on:
    repo: VanthStudios/UnityTemplateOpenSource
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: FakkQKJX3SRU+pHQ6eEfX0ZNB0iYwxNEbMJVb0/ySLZyMjF1uGwqgctKaToo7076KQla82gJS52lUySMm+SgHBdPEHfcJXDGtA5KW6aICedcaN6gxwJQ/cb8Y3bxBNCbqxSwqrcYIwz9R9lh9H9bwI6B5/+h8PvLqGliB7DhThjNkWCJWAOTMv3a30l262HJoKPpvU2YxLnwdVo0fxN1ya7vj8iVQuKl8RpHBi/uT+moS9iWygOrOukGYcRZhYLzNOFePYrMmDJ4H8aco1doScojipb17ukPZJ+oZswbDwfORLfnEBxzqnZ00b9NF1Jl3U53wwo7Uf7imY0fszmQRF6PsobQ+d8+eozzyF5eBJgwIEhPemj5ISO4KGpRH0Ky3EnWazciFew44nCxZycIxh1KmX/N5J8vPBRjLZVg7htBJpO89jDX3DPdfInj69asD2y2/WaBCeV0D3/YZHmixULKHrK/Q6SORnr6xrDqPQA4Y0ruSsJzBc4NZE1dNOU3N4J17eGy25c7NyNhQcxHM5LZw8w33w2z0qy3JrUh4D9wOTllVaboGA6fECmhyG/RAk+irQvw7qSf7P23aA0WwP/o2qaVPChbgSzw+EeMtUAuakw+Xko3xCRL3ywQR16rIe21rv3EAPwmh8FJqjJUpikM0pA2/S74nTEXgoJ8yYY=
